AWSTemplateFormatVersion: 2010-09-09
Description: |
  Cloudformation Template for kittens carousel static website deploy on s3. cloudfront and route 53
Parameters:
  KittensDomainName:
    Description: Enter your bucket name (full domain name)
    Type: String
    
Resources:

  KittensS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref paramBucketName
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerEnforced
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      WebsiteConfiguration:
        IndexDocument: index.html

  KittensBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref KittensS3Bucket # Required
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - 's3:GetObject'
            Effect: Allow
            Resource: !Join
              - ''
              - - 'arn:aws:s3:::'
                - !Ref KittensS3Bucket
                - /*
            Principal: '*'
  
  KittensCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      CertificateTransparencyLoggingPreference: "String"
      DomainName: !Ref KittensDomainName # Required
      DomainValidationOptions:
        - DomainName: !Ref KittensDomainName
          HostedZoneId: !Ref DomainName
      ValidationMethod: DNS


  KittenDNSName:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneId: !Ref DomainName
      RecordSets: 
        - Name: !Ref KittensDomainName
          Type: A
          AliasTarget:
            HostedZoneId: !Ref DomainName
            DNSName: !GetAtt KittensCloudfront.DomainName
           
Outputs:
  WebsiteURL:
    Value: !GetAtt KittensS3Bucket.WebsiteURL
    Description: URL for website hosted on S3
  S3BucketSecureURL:
    Value: !Join
      - ''
      - - 'https://'
        - !GetAtt
          - KittensS3Bucket
          - DomainName
    Description: Name of S3 bucket to hold website content